SELECT * FROM worker
WHERE SALARY > 100000;


SELECT FIRST_NAME, SALARY from worker;
SELECT 44+11;
SELECT now();

SELECT lcase('MANSI');
SELECT ucase('mansi');

SELECT * FROM worker
WHERE DEPARTMENT = 'HR';

# salary [80000, 300000] 
SELECT * FROM worker
WHERE SALARY BETWEEN 80000 AND 300000;

#reduce OR statement
#HR,ADMIN
SELECT *  FROM worker
WHERE DEPARTMENT = 'HR' OR DEPARTMENT = 'ADMIN';

#Better way : IN
SELECT * FROM worker
WHERE DEPARTMENT IN ('HR', 'ADMIN', 'Finance');

SELECT * FROM worker
WHERE DEPARTMENT NOT IN ('HR', 'ADMIN', 'Finance');

#wildcard
SELECT * from worker
WHERE FIRST_NAME LIKE 'a%';

#sorting using order by
SELECT * from worker
order by salary ;

# DISTINCT
SELECT DISTINCT DEPARTMENT from worker;

#Group by
SELECT DEPARTMENT, count(*) from worker Group by DEPARTMENT;

#aveg salary per DEPARTMENT
SELECT DEPARTMENT, AVG(SALARY) from worker
GROUP BY DEPARTMENT;

#MINIMUM
SELECT DEPARTMENT, MIN(SALARY) from worker
GROUP BY DEPARTMENT;

#MAXIMUM
SELECT DEPARTMENT, MAX(SALARY), sum(salary) from worker
GROUP BY DEPARTMENT;

#Group by with having
SELECT DEPARTMENT, count(DEPARTMENT) from worker GROUP BY DEPARTMENT
HAVING count(DEPARTMENT) > 2;